library(xlsx)
write.xlsx(f7(myupuni1,myupuni9), file="filename.xlsx", sheetName="sheet1", row.names=FALSE)
write.xlsx(f7(myupuni2,myupuni9), file="filename.xlsx", sheetName="sheet2", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni3,myupuni9), file="filename.xlsx", sheetName="sheet3", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni4,myupuni9), file="filename.xlsx", sheetName="sheet4", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni5,myupuni9), file="filename.xlsx", sheetName="sheet5", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni6,myupuni9), file="filename.xlsx", sheetName="sheet6", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni7,myupuni9), file="filename.xlsx", sheetName="sheet7", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni8,myupuni9), file="filename.xlsx", sheetName="sheet8", append=TRUE, row.names=FALSE)
write.xlsx(f7(myupuni9,myupuni9), file="filename.xlsx", sheetName="sheet9", append=TRUE, row.names=FALSE)

write.xlsx(f7(mydnuni1,mydnuni9), file="filename1.xlsx", sheetName="sheet1", row.names=FALSE)
write.xlsx(f7(mydnuni2,mydnuni9), file="filename1.xlsx", sheetName="sheet2", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni3,mydnuni9), file="filename1.xlsx", sheetName="sheet3", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni4,mydnuni9), file="filename1.xlsx", sheetName="sheet4", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni5,mydnuni9), file="filename1.xlsx", sheetName="sheet5", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni6,mydnuni9), file="filename1.xlsx", sheetName="sheet6", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni7,mydnuni9), file="filename1.xlsx", sheetName="sheet7", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni8,mydnuni9), file="filename1.xlsx", sheetName="sheet8", append=TRUE, row.names=FALSE)
write.xlsx(f7(mydnuni9,mydnuni9), file="filename1.xlsx", sheetName="sheet9", append=TRUE, row.names=FALSE)